2 problems :
#1. Fixed - after the better sollution to put the IO in try - finnally i forgot to remove closing the file when thread is stopping.
I.line 203, in run
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment

#2. I made some improvements but still cannot escape from sotrring in the memory. At least use better memory management now.
II.
fieldscoll.append(fields)
this soultion violates the " no storing in memory" requirement , any solution to this ?